# Generated by Django 4.2.5 on 2023-09-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descrption',
            new_name='description',
        ),
    ]
